import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Dallas's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="font-sans m-0 p-0 bg-gradient-to-br w-full min-h-screen from-slate-200 to-blue-300"
    >
      <body className="font-sans m-0 p-0">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
//className="flex-1 font-sans m-0 p-0 bg-gradient-to-br w-full min-h-screen from-slate-200 to-blue-300"
